-- CreateTable
CREATE TABLE "BrubeckStats" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dailyAPR" DOUBLE PRECISION NOT NULL,
    "dailyAPY" DOUBLE PRECISION NOT NULL,
    "spotAPR" DOUBLE PRECISION NOT NULL,
    "spotAPY" DOUBLE PRECISION NOT NULL,
    "dailyDataStaked" DOUBLE PRECISION NOT NULL,
    "spotDataStaked" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "BrubeckStats_pkey" PRIMARY KEY ("id")
);
